project_id = "rcgfrgxdsfdpvzkyltcp"

[functions.analyze-blog]
verify_jwt = true

[functions.analyze-cv]
verify_jwt = true

[functions.analyze-github]
verify_jwt = true

[functions.analyze-performance-review]
verify_jwt = true

[functions.generate-learning-path]
verify_jwt = true
